### PR TITLE
Create chrome extension and added instruction to README

### PR DESCRIPTION
**Pull request by eznix86**

### CODE REVIEW

**Comment by jhta** [comment]
Awesome! let me check it

**Comment by theArtechnology** [comment]
Well the png is not that awesome, maybe I should resize it.

**Review by jhta — APPROVED** [review]

**Comment by jhta** [comment]
@theArtechnology I gonna merge this, if you want you can send another PR improving the png size :)

**Comment by 0x15F9** [comment]
Hey. Could you assign the PNG-resize to me?

**Pull request merged**
